name: capybara_env
channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip

  # Core scientific stack
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - statsmodels
  - matplotlib
  - seaborn

  # Jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  
  # Bio/workflow (keep only what you really use)
  - biopython

  # PyTorch CPU build
  - pytorch=2.3.*
  - torchvision=0.18.*
  - cpuonly

  # Utils
  - hickle=5.0.2
  - tqdm>=4.64

  - pip:
      - torchmetrics>=1.4
      - git+https://github.com/aradha/recursive_feature_machines.git@pip_install
